# Generated by Django 6.0.4 on 2026-05-10 19:41

import apps.media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.media.models.origin_path)),
                ('original_filename', models.CharField(max_length=200)),
                ('file_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('video', 'Video')], max_length=20)),
                ('mime_type', models.CharField(max_length=100)),
                ('origin', models.CharField(choices=[('input', 'Input'), ('output', 'Output')], max_length=10)),
                ('size', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
