# Generated by Django 6.0.4 on 2026-05-10 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('url', 'URL')], default='text', max_length=10)),
                ('raw_text', models.TextField()),
                ('source_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input', to='media.mediafile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='processing.input')),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.CharField(choices=[('text', 'Text'), ('file', 'File')], default='file', max_length=100)),
                ('raw_text', models.TextField(null=True)),
                ('text_length', models.PositiveIntegerField(null=True)),
                ('audio_duration', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output', to='media.mediafile')),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='processing.operation')),
            ],
        ),
    ]
